CONTIKI_PROJECT = button
all: $(CONTIKI_PROJECT)

#UIP_CONF_IPV6=1
TARGET=avr-zigduino
AVRDUDE_PROGRAMMER=jtag3isp

CONTIKI = /home/user/looci/looci2-contiki-os/contiki-2.7
include $(CONTIKI)/Makefile.include
